gesdinet_jwt_refresh_token:
    ttl: 2592000          # 30 days
    user_provider: security.user.provider.concrete.app_user_provider
    single_use: true
    token_parameter_name: refresh_token
    firewall: api
