name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eventsphere_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo, pdo_pgsql, openssl, json
          tools: composer:2.9.5

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Create JWT directory
        run: mkdir -p config/jwt

      - name: Run Doctrine Migrations
        env:
          DATABASE_URL: "pgsql://postgres:postgres@127.0.0.1:5432/eventsphere_test"
        run: php -d error_reporting=E_ALL & ~E_USER_DEPRECATED vendor/bin/simple-phpunit --testdox
      - name: Run Tests
        env:
          DATABASE_URL: "pgsql://postgres:postgres@127.0.0.1:5432/eventsphere_test"
        run: php vendor/bin/simple-phpunit --testdox
